import "./globals.css";
import NavBar from "./Componens/Navbar/Navbar";
import Header from "./Componens/Header/Header";
import Footer from "./Componens/Footer/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import ScrollHandler from "./ScrollHandler";

export const metadata = {
  title: "Create single page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="RootLayout" suppressHydrationWarning={true}>
        <NavBar /> {/* Navbar sudah fixed, tidak perlu wrapper */}
        <Header />
        <main className="content-wrapper page-transition">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
