export async function GET() {
  const items = [
    {
      id: 1,
      name: "Flat white",
      desc: "1/2 susu, 1/2 espresso, es, karamel",
      price: "25000",
      catogry: "panas",
    },
    {
      id: 2,
      name: "Long black",
      desc: "1/4 krim, 3/4 espresso, es, kayu manis",
      price: "28000",
      catogry: "panas",
    },
    {
      id: 3,
      name: "Kopi Turki",
      desc: "1/3 susu, 2/3 espresso, es, vanila",
      price: "32000",
      catogry: "panas",
    },
    {
      id: 4,
      name: "Espresso",
      desc: "Tanpa susu, 1 espresso, es, karamel",
      price: "22000",
      catogry: "panas",
    },
    {
      id: 5,
      name: "Mocha",
      desc: "2/3 susu, 1/3 espresso, es, hazelnut",
      price: "30000",
      catogry: "panas",
    },
    {
      id: 6,
      name: "Caramel latte",
      desc: "1/4 krim, 3/4 espresso, es, kayu manis",
      price: "33000",
      catogry: "panas",
    },
    {
      id: 7,
      name: "Nitro cold brew",
      desc: "1/2 susu, 1/2 espresso, es, karamel",
      price: "38000",
      catogry: "panas",
    },
    {
      id: 8,
      name: "Cafe",
      desc: "1/3 susu, 2/3 espresso, es, vanila",
      price: "27000",
      catogry: "panas",
    },
    {
      id: 9,
      name: "Mangga",
      desc: "mangga, susu, gula",
      price: "18000",
      catogry: "jus",
    },
    {
      id: 10,
      name: "Apel",
      desc: "apel, gula, buah-buahan",
      price: "20000",
      catogry: "jus",
    },
    {
      id: 11,
      name: "Stroberi",
      desc: "1/3 susu, stroberi",
      price: "22000",
      catogry: "jus",
    },
    {
      id: 12,
      name: "Kiwi",
      desc: "1/3 susu, 2/3 kiwi",
      price: "23000",
      catogry: "jus",
    },
    {
      id: 13,
      name: "Jeruk",
      desc: "jeruk, gula, lemon",
      price: "15000",
      catogry: "jus",
    },
    {
      id: 14,
      name: "Kue keju",
      desc: "keju, gula, buah-buahan",
      price: "35000",
      catogry: "pencuci mulut",
    },
    {
      id: 15,
      name: "Pancake",
      desc: "1/3 susu, cokelat",
      price: "32000",
      catogry: "pencuci mulut",
    },
    {
      id: 16,
      name: "Tart karamel",
      desc: "1/3 susu, 2/3 karamel",
      price: "38000",
      catogry: "pencuci mulut",
    },
    {
      id: 17,
      name: "Kue vanila",
      desc: "vanila, gula, susu",
      price: "30000",
      catogry: "pencuci mulut",
    },
    {
      id: 18,
      name: "Air mineral kecil",
      desc: "air mineral kemasan kecil",
      price: "5000",
      catogry: "minuman ringan",
    },
    {
      id: 19,
      name: "Pepsi",
      desc: "minuman bersoda cola",
      price: "8000",
      catogry: "minuman ringan",
    },
    {
      id: 20,
      name: "Cherry cola",
      desc: "cola rasa cherry",
      price: "10000",
      catogry: "minuman ringan",
    },
    {
      id: 21,
      name: "Red Bull",
      desc: "minuman energi",
      price: "15000",
      catogry: "minuman ringan",
    },
  ];

  return new Response(JSON.stringify(items), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}
